### ISSUE TITLE
What is the correct StatsD address to use within my containers?

### ISSUE THREAD

**Issue by brendanjerwin** [convox-examples/dd-agent#1]
The data dog agent is a forwarder of StatsD as well as a collector. I want to be able to submit metrics from within my applications.

**Comment by nzoschke** [comment]
Good question, I'm just learning about this part of Datadog now.

It looks like we can't use this part of Datadog right now.

Is submitting metrics directly to the Datadog API an option? http://docs.datadoghq.com/guides/metrics/#methods

The docs are here:

http://docs.datadoghq.com/guides/metrics/
http://docs.datadoghq.com/guides/dogstatsd/
http://docs.datadoghq.com/guides/dogstatsd/#configuration

> DogStatsD accepts custom application metrics points over UDP, and then periodically aggregates and forwards the metrics to Datadog

> dogstatsd_port: 8125

So I think its a question of exposing UDP port 8125 on the datadog agent container.

That isn't possible yet with this Convox app approach.

I also don't see this considered in the official Datadog ECS integration. I would expect a UDP PortMapping directive on the task

http://docs.datadoghq.com/integrations/ecs/
http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_PortMapping.html

**Comment by robinjoseph08** [comment]
This has been addressed with https://github.com/convox-examples/dd-agent/pull/3, right?

**Comment by nzoschke** [comment]
Correct. The docker-compose and readme have been updated to demonstrate sending metrics to the statsd collector.
